from D1111.BST import *

t = BST()
t.root = t.put(44,'복숭아')
t.put(90,'수박')
t.put(15,'체리')
t.put(22,'망고')
t.put(33,'무화과')
t.put(24,'감')
t.put(38,'포도')
t.put(8,'살구')
t.put(47,'토마토')
t.put(78,'고구마')
t.put(11,'키위')
t.put(38,'배')
t.put(46,'바나나')
t.put(16,'사과')
t.inOrder(t.root)
print()
t.delete(90)
t.inOrder(t.root)
print()
print(t.get(44)) #검색
print(t.min().value)